

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=webhook_service
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 3
    volumes:
      - .:/app  # You may remove this in production if not needed
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_SwdbrNq1QIi4@ep-withered-mouse-a40or4mx-pooler.us-east-1.aws.neon.tech/webhook-url?sslmode=require
      - REDIS_URL=redis://redis:6379/0
      - MAX_RETRY_ATTEMPTS=5
      - LOG_RETENTION_HOURS=72
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  worker:
    build: .
    command: celery -A app.tasks.worker worker --loglevel=info -Q deliveries,cleanup -E -n worker.%%h
    volumes:
      - .:/app  # You may remove this in production if not needed
    depends_on:
      - db
      - redis
    environment:
      - CELERY_HOSTNAME=worker-${HOSTNAME}
      - DATABASE_URL=postgresql://neondb_owner:npg_SwdbrNq1QIi4@ep-withered-mouse-a40or4mx-pooler.us-east-1.aws.neon.tech/webhook-url?sslmode=require
      - REDIS_URL=redis://redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s
    scale: 8

volumes:
  postgres_data:
